### ISSUE TITLE
ORFの出展内容を決める

### ISSUE THREAD

**Issue by miyukki** [sfc-arch/documents#12]
### ORF開催概要

| テーマ | 次世紀の芽~25年目に100年後を考える~ |
|:---:|:---|
| 日時 | 2015年11月20日(金)~21日(土) |
| 場所 | 東京ミッドタウン ホール |

#### ホール内ブース展示

* 木製の軸組み(柱)に囲まれた直行座標で区切られたスペースです。
* 900mm四方の小間を最大24小間まで申請可能です。ただし、必ずしもご希望に添えない場合がありますので、あらかじめご了承ください。
* 割り当てられたスペース内で、自由な発想による発表スタイルで、展示空間を作り出していただきます。
* 出展内容登録後に、アルゴリズム(※松川研究室にて開発)を用いてグルーピングや隣接関係を生成し、小間配置を行います。

##### 展示可能範囲

| 面積 | 割当てられた小間の範囲内 |
|:---:|:---|
| 高さ | 原則2200mm以内 |
| 耐加重 | 500kg/m²以内 |

* 上記は避難障害、自動火災報知設備の感知障害、スプリンクラーの散水障害、誘導灯の視認障害等とならないようにするための要件。
* カーテン、幕、のぼり、展示用合板その他装飾品は、必ず、防炎性能を有す るものを使用してください。遵守いただけない場合は、当日、即時撤去していただきますので、あらかじめご了承ください。

##### 禁止事項

* 屋根、キャノピー(天蓋、庇等)を架けるような施工
* 火気の使用、発火または引火性の物品や危険物の持ち込み
* 大音量、振動、悪臭の発生など、来場者や周囲の出展者に迷惑をかける、または、不快感を及ぼす恐れのある行為や発表形態
* 非常口を塞ぐ施工や発表形態

##### 貸出可能な什器等

* ポスターフレーム(A1サイズ)
* ポスターフレームを吊るためのワイヤーあるいは鎖と金具(壁沿いのスペースがある場合のみ使用可能)
* イーゼル
* 折りたたみテーブル(W1800mm×D450mm×H700mm)
* 椅子

※ 必ずしも台数等ご希望に添えない場合がありますので、あらかじめご了承ください。
※ ポスターを展示するにあたり、東京ミッドタウンの設備や什器を傷つけるような方法は厳禁とします(粘着テープ・両面テープ・画鋲等で、直接壁面やテーブルに貼ることはできません)。
※ ホール外通路スペースでのポスター展示の場合、通路確保のため、長机の奥行き(約45cm)以上に大きい什器等を設置することはできません。

折りたたみテーブル・椅子サイズ感イメージ

![2015-08-05 10 24 36](https://cloud.githubusercontent.com/assets/2297122/9076364/648c75ac-3b5c-11e5-8ba4-f804f5ba0c76.png)

### その他注意事項

木製の軸組み(柱)に対し、以下の行為は禁止とします

* 塗料で着色する行為
* ノコギリ等で切断する行為
* 人為的に取り外す行為

出展にあたり、以下の行為を予定している方は、9月30日(水)までに、必ず、 ORF事務局までご一報ください。事前にご相談がない場合は、当日、即刻当該行為を中止していただきます。また、内容によっては、実施いただけない可能性もありますので、あらかじめご了承ください。

* 食品を配布する、試飲または試食を提供する行為
* 動植物を持ち込む行為
* 会場を汚す恐れのあるものを持ち込む行為(土、水等)
* 東京ミッドタウン ホールおよびカンファレンス以外での活動行為(街頭インタビュー、アンケート、メディアの生放送等)

**Comment by demmys** [comment]
## 村井研での出展申請

### 締切
2015年8月12日(水) 23:59 JST

### 申請内容

#### プロジェクト情報
* タイトル（和文・英文）
* 概要（和文250文字、英文800文字まで）
* 関連URL（任意）
* 担当者氏名（和文・英文）
* 担当者所属
* 担当者職名
* プロジェクトを表すロゴ、写真、イラスト等（1000ピクセル四方以上のJPEG画像ファイル）

#### ブース希望情報
* 希望展示タイプ（ホール内orホール外通路）
* 希望小間数
* 隣接希望団体の有無（有りの場合団体名）
* ポスター枚数
* イーゼル台数
* 折り畳みテーブル数
* 折りたたみ椅子数
* 展示模型　大きさ
* 独自施行有無
* 音響有無
* 備考

**Comment by demmys** [comment]
@sfc-arch/owners 
Archメンバーは自分が出展するつもりかどうか、出展するつもりならなにを出すつもりかを、**全員**ここに書いてください。
もちろん、スペースの都合上から考えている通りの形で出展できるとは限りませんが、出展希望した人は最悪でもポスターかディスプレイでまとめて研究内容を表示するくらいはできるようにするつもりです。

**Comment by Akkyie** [comment]
誰も書いてなくて不安なのですが、たぶん出展します
やってる内容的に端末を何台か並べて…みたいなのが理想的ですが、それで面白いことできるかどうかわからないのでポスターの端っこに載せてもらえれば十分な気がしてます

**Comment by pasora** [comment]
出展します
NFCを軸で考えてますけど…って感じです

**Comment by miyukki** [comment]
私もFPGAの映像関係で出展したいな…

**Comment by kut2uky** [comment]
全く思いつかないので出展はしません…

**Comment by usk83** [comment]
出典してみたな、とは思うのですが、いかんせん研究らしい研究をしていないためなんとも...

**Comment by demmys** [comment]
あ、ちなみに自分はTreeSwiftでどうにかして出すつもりです。

**Comment by seibe** [comment]
言い出しっぺの一人として出します。
卒論含め過去作は全て出せる。もち全部WEB。
誰かと組んで新作を作るもよし。

**Comment by demmys** [comment]
@tmatsuya @sora @miyukki @seibe @Akkyie @pasora @shunkino 
とりあえず、何かしら出すものを言ってくれた人々 + Maker Fairで出したものは出す前提でプロジェクト申請をしようと思います。

| 仮プロジェクト名 | 内容 | 代表者 |
|:---:|:---:|:---:|
| バーチャル・ロボット・アバター | プラダンボーくんの目線をヘッドマウントディスプレイでリアルタイムに見られる映像伝送システム。IPにのせるかも。 | macchan |
| 低遅延4K IP配信プロジェクト | 4Kでの中継映像をSFC-六本木間の100G Erther越しにに配信するプロジェクト | miyukki |
| 近距離無線通信プロジェクト | Bluetoothによるメッシュネットワークを用いたモバイル機器間の情報共有システム (aky)、NFCを用いたシステム (pasora) | pasora |
| コンパイラ / IoT / Web | Internet of Porker (sora)、TreeSwift (demmy)、seibeのやつ | sora |

で、とても時間がないのですが、各プロジェクトごとに

* タイトル（和文・英文）
* 概要（和文250文字、英文800文字まで）
* 関連URL（任意）
* 担当者氏名（和文・英文）
* 担当者所属
* 担当者職名
* プロジェクトを表すロゴ、写真、イラスト等（1000ピクセル四方以上のJPEG画像ファイル）

を提出する必要があるので、それぞれ*明日までに*考えて出してもらう必要があります。

**Comment by demmys** [comment]
ちなみに上に載っていない人は、なにをやるか決めたらどこかの机を少しスペース借りてやる感じになります。

**Comment by pasora** [comment]
* タイトル（和文・英文）
近距離通信技術とP2Pネットワーク
Short-range communication technologies and P2P networks

* 概要（和文250文字、英文800文字まで）
端末間で無線通信をする手段は、Wi-Fiだけではありません。
我々はBluetoothやNFCといった近距離に限定した新しい通信のカタチを研究しています。
Your devices don't have to use Wi-Fi to communicate with each other.
We propose new communication style by short-range wireless technologies such as Bluetooth or NFC.

* 関連URL（任意）
none

* 担当者氏名（和文・英文）
原 雅彦
Masahiko Hara

* 担当者所属
環境情報学部

* 担当者職名
学生

* プロジェクトを表すロゴ、写真、イラスト等（1000ピクセル四方以上のJPEG画像ファイル）
?

**Comment by miyukki** [comment]
* タイトル（和文・英文）
遠隔スイッチング可能な低遅延4K映像IP伝送システム
Remote switchable low-latency 4K video over IP.

* 概要（和文250文字、英文800文字まで）
（修正中）

* 関連URL（任意）
N/A

* 担当者氏名（和文・英文）
山中 勇成
Yusei Yamanaka

* 担当者所属
環境情報学部

* 担当者職名
学生

**Comment by demmys** [comment]
* タイトル (和文・英文)
Arch研究グループ
Arch research group

* 概要（和文250文字、英文800文字まで）
Archは次世代のネットワークおよびコンピュータ・アーキテクチャの実装と運用について研究しているグループです。本展示では、IoTデバイス、Webベースアプリケーションおよびコンパイラの実装に関する研究をご紹介いたします。
We propose, build and manage the next-generation network architecture and computer architecture. In this exhibition, we will present you our researches related to an IoT device, a web based application and a compiler implementation.


* 関連URL（任意）
arch.sfc.wide.ad.jp

* 担当者氏名（和文・英文）
soraさん

* 担当者所属
政策・メディア研究科

* 担当者職名
後で

* プロジェクトを表すロゴ、写真、イラスト等（1000ピクセル四方以上のJPEG画像ファイル）
Archロゴ
