### ISSUE TITLE
初回RG-Coordinatorミーティングで話す必要のあること

### ISSUE THREAD

**Issue by demmys** [sfc-arch/documents#14]
意見や内容について先に行っておきたいことなど、気づいたことのある人がいれば随時コメントしてください。

## RG-guidanceなる何か

RGの履修を考えている人向けの説明会をやっているらしい

```
【内容】
– 合同研究室概要説明
– 履修者体験談
– 個別履修相談
– 研究室ツアー
```
※ SFC CLIPの記事より引用

* 教室を確保する必要性 (先学期はmeliさんが予約したらしい)
* 認知を広める必要性
* 2015sではSFC CLIPに告知しているので、これやるなら早めに動く必要がありそう。 @Akkyie がわかりそう。(ref: [春学期の告知記事](http://sfcclip.net/message2015040302/))

## 初回RG関連

* 各KGの紹介は形式を変える必要がなさそうなので、スライドを集めたりポスターをリマインドする係を決めて動き出したい
* 一緒にKGの存在確認もするのが良さそう
* KGツアーするなら時間を決めて早めに各KGに通知?
* 春学期は卒論係のMTGがあったが、秋は必要ない?
* 新人MLのための連絡先回収 (春学期は Google Formでやったらしい)

## 新人歓迎会関連

* 予算などの決定が必要 (担当を決める)
* おおよその出席人数を把握する必要性がありそう
* ごはん (春学期は :pizza: ← 車で運ぶととても安い（とても）)

## RGレク関連

例年4週目あたりにRGレクをやる

* 団体登録しているはずなので、どうなっているのか確認する (ref: [スポーツ施設の利用登録に関するページ](http://f-mirai.jp/sports/registration))
* 上記登録を確認した上で秋葉台体育館の予約が必要
* 春学期はドッジボールとバスケットボールをやったらしい

## Webページ関連

* 履修希望者向け説明ページのHTMLがver 4.01...
* 卒論/修論の一覧ページが管理されてない (RG Gitで管理されているっぽい)
* https://github.com/sfc-arch/rg-team-io
* WIP/TERM/卒論のコメントとか資料アップロードとかがイケてない(そもそもFail/Pass管理機能がない)
* 毎回Wikiを作るのは色々無駄

## ML関連

* demmyとboroがrg-coordinator[at]に各KGで必要な人間を追加
* 新人がメールアドレスを手に入れるまでの間の連絡用ML(newcomer-2015f[at])の管理者を決める
* KGLの確認担当を決める(kgl[at]の管理)
* Facultyの確認担当を決める(faculty[at]の管理)
* www-adminの管理担当を決める

## 授業関連

demmyが初回MTGまでに授業計画の草案を作成予定...

* 毎回の授業教室の確保はどうなってる? (i21)
* 英語対応について(Coordinatorに英語対応できる人いるか)
* jun/hxtの講義のための日程確保が必要か否か
* 各講座の担当ぎめ
* 村井研側では成績にRG授業の出席を一切見られていない件について

### GithubでオープンなCoordinatorはいかが?
* 引き継ぎ資料の作成が無駄感...
* git.sfc.wide.ad.jp の使いづらさすごい
* タスク管理とWebページ管理と資料管理とミーティングログと...がバラバラなのつらい
* 秘匿する必要のある情報はプライベートレポジトリを作れる
* とりあえずsfc-archで運用するのはあり

### htxサイドもSlack使いませんか
* リアルタイムかつオープンなコミュニケーションがしたい
* Slackbotで色々インテグレーションして楽したい

### 日程関連

* 秋学期の授業日程を確認
* 夏季休業中のCoordinatorミーティングの日程を確認

## WIP/TERM/卒論関連

* WIP/TERM/卒論/成績付けの日程候補を確認してjun/hxtの日程確保
* 卒論係は通年のはずなので、連絡を取る必要がある (やりとりする担当を決める。jun側は掛け持ちしてる @Phi-phi ?)
* 無駄な時間が多すぎる問題 (自分の発表以外出席必須にする必要はないのでは)
* 学部生のログ必要か? どうせ正確じゃないので、動画アーカイブすればいいのでは
* 予稿や卒論のフォーマットが管理されてなさすぎる問題
* そもそも予稿活用されてなさすぎ問題
* TERMや卒論のPass/Failが曖昧問題 (特にPassの通知とか来ない)

## 村井研独自

* 鍵申請の担当を決める (毎期とても遅い)
* 旧森川研所属者などの扱いを確認する

**Comment by Akkyie** [comment]
メンションが付いたので…
MESSAGEは送った内容をそのまま載せてもらうだけなので、内容が決まり次第CLIPにメールを送ればすぐに載るかと
あと余談ですがMarkdownで記事書いてるので使えば反映されると思います

**Comment by pasora** [comment]
レク、要りますかね:basketball::soccer::baseball::bowling::space_invader:

**Comment by miyukki** [comment]
@pasora @demmys レクやったほうがいいという人の気持ちはわかるけど、体育館とか使えないのかな

**Comment by kucats** [comment]
前にcoordinatorしたときに、その話は出たけど、予約できる団体の制限で(協議会みたいなのがある？)無理という話だった

2015年8月20日木曜日、Yusei Yamanaka<notifications@github.com>さんは書きました:

> @pasora <https://github.com/pasora> @demmys <https://github.com/demmys>
> レクやったほうがいいという人の気持ちはわかるけど、体育館とか使えないのかな
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sfc-arch/documents/issues/14#issuecomment-132896371>.
>


-- 
--
沖 幸太朗 <kotaro@ko.gs>
050-3630-6731

**Comment by demmys** [comment]
運動をした方がいい、という意見は理不尽なほどに論破しづらい上に、junの意向と合ってるからなあ。
kucatsの言うとおり、アリーナ使うのは簡単ではないらしいので、従来通りの形になるのは致し方無いかなあと思う。

**Comment by pasora** [comment]
自分もその気持ちはわかるけど、この現状にその気持ちだけでやってくれるなって話。
論破できようができなかろうが来なけりゃしょうがないし、
やるんなら我々はもうちょいちゃんとやらねばなぁ。

**Comment by demmys** [comment]
@pasora 
ただしい。
KG対抗の景品付きトーナメントにする、とかがすごく普通の案だけど。
お金で解決系。

**Comment by miyukki** [comment]
@demmys @pasora そこの体育館でパーティーとかできないの？

**Comment by pasora** [comment]
KG対抗、良いと思います
ただ人数バラつくので点数は出席率で傾斜かけるとかうまくやらないと…競技も選ばないと…ですね

体育館飲食禁止では
パーティーなら食堂貸しきったほうが(できるかどうかわからん

**Comment by miyukki** [comment]
これで予算決めようよ

**Comment by demmys** [comment]
@pasora 
人数は、少ないところはくっつける、ってことはできるよね。
@miyukki の言うこれっていうのは、対抗戦ってこと? パーティーとは

**Comment by miyukki** [comment]
@demmys 対抗戦でなにかもらえる（今後影響の出そうなもの）であれば絶対出そう（出たこと無い
