### ISSUE TITLE
コミケC89の賛同者を決める

### ISSUE THREAD

**Issue by miyukki** [sfc-arch/documents#15]
賛同者: @seibe @miyukki

**Comment by seibe** [comment]
私はjsx (Adobe javascript extension)ネタで書くつもり

**Comment by demmys** [comment]
出すのであれば、Swiftネタで書く。
研究っぽいのはあんまりやりたくない。
書くとしたら、SwiftでAndroidアプリ開発、か、モダンな言語のコンパイラ実装法、みたいな、そっち系。

**Comment by seibe** [comment]
賛同者が少ないということで、KGとして何かを出すのは断念したいと思います。賛同あるいは応援してくださった皆さん、どうもありがとうございます。
なお、私のjsxネタはコツコツ懲りずに書き始めようかと思います。
