### ISSUE TITLE
RG Portalを作る

### ISSUE THREAD

**Issue by miyukki** [sfc-arch/documents#16]
https://github.com/sfc-arch/documents/issues/14

- 履修希望者向け説明ページのHTMLがver 4.01...
- 卒論/修論の一覧ページが管理されてない (RG Gitで管理されているっぽい)
- WIP/TERM/卒論のコメントとか資料アップロードとかがイケてない(そもそもFail/Pass管理機能がない)
- 毎回Wikiを作るのは色々無駄

ここらへんの問題点を解決するため、RG内のインターナルな情報サイトを作る。

## URL
http://portal.gw.sfc.wide.ad.jp/

## 機能
- [x] Wiki的な記事の作成機能
- [x] 出席のチェック機能
- [ ] RGの人検索機能
- [x] Slackのログ検索機能
- [x] 資料のアップローダー機能
- [x] Fail/Pass管理機能
など

**Comment by demmys** [comment]
とりあえずOKでしょう
