### ISSUE TITLE
ORF必要情報の申請

### ISSUE THREAD

**Issue by demmys** [sfc-arch/documents#17]
2015年9月30日(水) 23:59 JST
までに以下の情報を書くプロジェクト申請する必要がある。

今年のネットワークは原則無線で、
プライベートアドレスの割当になるそうです。
有線やグローバルアドレスが必要な方は、
ネットワークの項目を記入の上、ご連絡ください。

----------------------

* 出展者情報（必須）
希望電源口数:
予定使用総電力(W):
ポスターフレーム数:
往路搬送有無:
復路搬送有無:
外部運送業者利用有無:
ダンボール以外搬送荷物の有無:

* 保証対象物品（希望者のみ）
名称:
型式:
時価額:

* ネットワーク（希望者のみ）
有線ネットワーク使用の有無:
有線ネットワークの使用ポート数:
固定IPv4(プライベート)アドレスの希望割当数:
固定IPv4(グローバル)アドレスの希望割当数:
無線LANにおける固定アドレス(プライベート・グローバル)の割り当て希望数:

**Comment by demmys** [comment]
@tmatsuya @miyukki @sora @pasora @Akkyie @seibe 
各々必要な
* 電源口数
* 使用総電力
* ポスターフレーム数
* 搬送有無
* 有線ネットワーク仕様の有無 (使用する場合ポート数・固定IPの希望割当数)
* 無線LANでの固定アドレス割当希望数

を教えて下さい。
あと、 @tmatsuya さん、 @sora さんはこれまで出していた感じからこう書いたほうがいい、などあれば一緒に教えていただけると助かります。

**Comment by Akkyie** [comment]
@demmys 
- 3
- 30W
- 0
- 無し
- 無し
- 0
でお願いします

**Comment by tmatsuya** [comment]
@demmys よろしく。ポスターは必須だと思うので、それぞれ最低１個はポスターフレームいるでしょう。段ボールでの搬送しないと、帰りの打ち上げとか大変だよ。

出展者情報（必須）

希望電源口数:12
予定使用総電力(W):300W
ポスターフレーム数:1
往路搬送有無:あり
復路搬送有無:あり
外部運送業者利用有無:なし
ダンボール以外搬送荷物の有無:なし

ネットワーク（希望者のみ）
有線ネットワーク使用の有無:あり
有線ネットワークの使用ポート数:4
固定IPv4(プライベート)アドレスの希望割当数:0
固定IPv4(グローバル)アドレスの希望割当数:0
無線LANにおける固定アドレス(プライベート・グローバル)の割り当て希望数:0

**Comment by pasora** [comment]
電源口数:2
使用総電力:100W
ポスターフレーム数:1
搬送有無:なし
有線ネットワーク仕様の有無 (使用する場合ポート数・固定IPの希望割当数):なし
無線LANでの固定アドレス割当希望数:なし

おねがいします

**Comment by seibe** [comment]
電源口数：3
使用総電力：30W
ポスターフレーム数：1
搬送有無：なし
有線ネットワーク仕様の有無 (使用する場合ポート数・固定IPの希望割当数)：なし
無線LANでの固定アドレス割当希望数：なし

**Comment by sora** [comment]
あれ, 俺なにか展示するんだっけ...
seibeとかのを展示する代表者として名前いれただけじゃなかったっけ。

まっちゃんぐみの手伝いをする予定なので、自分からは何もありません。 であってるかな。

**Comment by demmys** [comment]
送ったなり
