### ISSUE TITLE
初回RGのためのスライドとポスター作成

### ISSUE THREAD

**Issue by demmys** [sfc-arch/documents#18]
スライドはdemmyが作ります。
ポスターは @seibe にお願いしたはず。

**Comment by seibe** [comment]
はい、ポスター承っております。
今のところ、先学期のを少し書き換えるだけの予定。

**Comment by seibe** [comment]
KGポスターを更新したので、確認お願いします @demmys 
https://github.com/sfc-arch/_documents/tree/master/assets/2015s
