### ISSUE TITLE
次回輪講の本を決める

### ISSUE THREAD

**Issue by miyukki** [sfc-arch/documents#19]
Rodさんより見本いただいた本をリストに。

- [モダンオペレーティングシステム](
http://www.amazon.co.jp/%E3%83%A2%E3%83%80%E3%83%B3-%E3%82%AA%E3%83%9A%E3%83%AC%E3%83%BC%E3%83%86%E3%82%A3%E3%83%B3%E3%82%B0-%E3%82%B7%E3%82%B9%E3%83%86%E3%83%A0-%E5%8E%9F%E6%9B%B8-%E7%AC%AC2%E7%89%88/dp/4894715376)
OSの構成について書かれている。プロセス、スレッド、メモリ管理、入出力、ファイルシステムなど。

- [Artificial Intelligence A Modern Approach](http://www.amazon.co.jp/Artificial-Intelligence-Stuart-Russell-Norvig/dp/9332518696)

- [Structured Parallel Programming](http://www.amazon.co.jp/Structured-Parallel-Programming-Efficient-Computation/dp/0124159931)
構造化並列プログラミング

- [Distributed Systems: Concepts and Design](http://www.amazon.com/Distributed-Systems-Concepts-Design-Edition/dp/0132143011)

- [Design and Implementation of the FreeBSD Operating System](http://www.amazon.co.jp/Design-Implementation-FreeBSD-Operating-System/dp/0201702452)

- [Statistics: An Introduction using R](http://www.amazon.co.jp/Statistics-An-Introduction-using-R/dp/0470022981)

- [Introduction to Algorithms] (http://www.amazon.co.jp/Introduction-Algorithms-Thomas-H-Cormen/dp/0262533057)

- [Linux システムプログラミング](http://www.amazon.co.jp/Linux%E3%82%B7%E3%82%B9%E3%83%86%E3%83%A0%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%9F%E3%83%B3%E3%82%B0-Robert-Love/dp/4873113628)
オライリー。ファイルI/O、プロセス管理、メモリ、シグナル、GCC拡張。

- [Advanced Programming in the UNIX Environment](http://www.amazon.co.jp/Programming-Environment-Addison-Wesley-Professional-Computing/dp/0201563177)
詳解UNIXプログラミングの原書。UNIX実装、ISO C、POSIX、ファイルI/O、プロセス管理、シグナル、スレッド。

**Comment by pasora** [comment]
[モダンオペレーティングシステム](
http://www.amazon.co.jp/%E3%83%A2%E3%83%80%E3%83%B3-%E3%82%AA%E3%83%9A%E3%83%AC%E3%83%BC%E3%83%86%E3%82%A3%E3%83%B3%E3%82%B0-%E3%82%B7%E3%82%B9%E3%83%86%E3%83%A0-%E5%8E%9F%E6%9B%B8-%E7%AC%AC2%E7%89%88/dp/4894715376)
[Artificial Intelligence A Modern Approach](http://www.amazon.co.jp/Artificial-Intelligence-Stuart-Russell-Norvig/dp/9332518696)
[Structured Parallel Programming](http://www.amazon.co.jp/Structured-Parallel-Programming-Efficient-Computation/dp/0124159931)
[Distributed Systems: Concepts and Design](http://www.amazon.com/Distributed-Systems-Concepts-Design-Edition/dp/0132143011)
by ロッドさん

**Comment by pasora** [comment]
[Design and Implementation of the FreeBSD Operating System](http://www.amazon.co.jp/Design-Implementation-FreeBSD-Operating-System/dp/0201702452)
[Statistics: An Introduction using R](http://www.amazon.co.jp/Statistics-An-Introduction-using-R/dp/0470022981)
Introduction to Algorithms [MIT](https://mitpress.mit.edu/books/introduction-algorithms), [Amazon](http://www.amazon.co.jp/Introduction-Algorithms-Thomas-H-Cormen/dp/0262533057)
[Linux システムプログラミング](http://www.amazon.co.jp/Linux%E3%82%B7%E3%82%B9%E3%83%86%E3%83%A0%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%9F%E3%83%B3%E3%82%B0-Robert-Love/dp/4873113628)
[Advanced Programming in the UNIX Environment](http://www.amazon.co.jp/Programming-Environment-Addison-Wesley-Professional-Computing/dp/0201563177)
by ロッドさん
