### ISSUE TITLE
ORFスペース割当ミーティング

### ISSUE THREAD

**Issue by demmys** [sfc-arch/documents#23]
時間:
10月27日(火) 16:30~18:00

場所:
ΔN111(予約済み)

参加予定:
zero3さん、aoさん、takafumiさん 他

参加までの宿題:
ミーティング当日までにプロジェクトで必要となるスペースの大きさ
(特に机上のスペースの大きさとポスターの枚数)
を具体的に決めておくこと

**Comment by demmys** [comment]
村井研で確保されている場所の情報

-----
ORFブース展示ですが、希望申し込みコマ数24コマに対して、
割当コマ数が12コマ(1コマ90cm四方、3*4コマ)となりました。

それに対して、ポスター15枚、展示模型3つなど
かなりスペース的に厳しい状況で、
机8個、椅子10個を全て配置することは難しいかと思います。
なのでイーゼルを10個申し込みしておきましたので、
ポスター展示や模型展示など各プロジェクト間で協力してスペースをご使用ください。

申し込み内容は下記の通りです。
椅子 10 -> 10
机 8 -> 10
ポスター枚数 15 -> 15
ポスターフレーム数 14 -> 15
イーゼル 2 -> 10
電源口数 32 -> 40
電力(W) 1800 -> 3000
有線ポート数 4 -> 4

電源周りに関しては今回タコ足配線厳禁とのことで、
希望数より多めに申し込んであります。

荷物搬送に関しては、
集荷日：2015年11月18日（水）予定
返却日：2015年11月22日（日）予定
ダンボール(大): 10個
ダンボール(小): 10個
集荷,返却場所: デルタ棟
で申し込んであります。
-----

**Comment by demmys** [comment]
話し合いを始める元になったdemmyからのメール内容

-----
申請の時こそORF実行委員会の方に指定された「小間」という単位を使用していましたが、
実際には小間毎に仕切りをつくるわけではないので、
それよりも小さい単位で分け合うことになるかと思います。

小間が長方形である以上机の置き方のパターンは限られておりますので、
恐らく最も調整が必要なのは机の上のスペースです。
そこを決めればポスターの場所、それぞれのグループが何人くらい人を置けるか、
などは自ずと決まってくるかと思います。

Archメンバーによる各プロジェクトに確認した結果、

「Arch研究グループ」 - 机: 0.7台分のスペース, ポスター: 2枚
「近距離通信技術とP2Pネットワーク」 - 机: 0.5台分のスペース, ポスター: 2枚
「遠隔スイッチング可能な低遅延4K映像IP伝送システム」 机0.8台分のスペース, ポスター: 1枚

が最低でも必要だということになりました。
ただ、主に机の上のスペースを特に必要としてかさばっているのはディスプレイなので、
これを床に置くなどしてうまく調整できるところはあるかもしれません。

説明員はスペースの大きさから見て基本は各プロジェクト1名、一部2名というのが限界かと思います。

-----

**Comment by demmys** [comment]
各プロジェクトが

* 机の上のスペースをどのくらい使用するか (特にディスプレイの台数等が関わってきそう)
* ポスターを何枚掲示するか (できるだけ壁に貼り、無理な分はイーゼルで配置)

を見極めた上で、スペース内をどういうレイアウトでどう割り当てるか、を決める必要がある。

**Comment by demmys** [comment]
Archのスペースの詳細については

「Arch研究グループ」 - 机: 0.7台分のスペース, ポスター: 2枚
* demmyのSwiftにMacBook 1台、seibeのプレゼンシステムにPC 1台とディスプレイ1台を見せられるスペースとそれぞれのポスター

「近距離通信技術とP2Pネットワーク」 - 机: 0.5台分のスペース, ポスター: 2枚
* pasoraのNFC可視化にディスプレイとAndroid端末各1台、akyのメッシュネットワーク可視化にiOS端末最大5台 (スマホ・タブレット混合)とそれぞれのポスター

「遠隔スイッチング可能な低遅延4K映像IP伝送システム」 机0.8台分のスペース, ポスター: 1枚
* miyukkiの感覚に任せるが、ディスプレイ2台とスイッチ・FPGA・カメラを立体的に配置すれば角など使ってうまくできそう?

という感じ

**Comment by demmys** [comment]
もしあまり人が集まらなかったら、

* どうやってスペースを決めていくか
* 例年どういう風にしていたか
* 来ていないプロジェクトと誰がどうすれば連絡を取れるか

とかを話し合って欲しい

**Comment by miyukki** [comment]
ミーティングの結果

- AQUA
  PCモニター用ディスプレイ1枚
  ポスター1枚
  90cm四方くらいの机があればよい
  電源はディスプレイとラップトップ、ネットを使うでもはやらないので無線で大丈夫

- kumo
  ポスターは最大2
  机はほぼいらない（必要なら1台
  できたらiPhoneアプリの展示をするかも

**Comment by demmys** [comment]
* soiはポスター一枚
* AWAは2コマポスター2枚を要望で展示の要望はなし

**Comment by demmys** [comment]
> AQUAの岡です。火曜日に、miyukkiさんを含めた3人で、ORF村井研側の割り当て
> ミーティングをやりました。
> その際、AQUAの場所(壁際か否か)については、特に希望なしと申しましたが、そ
> れについて変更があります。
> ポスターを1枚貼るため、壁際に構えるか、もしくはイーゼルを1つ確保していた
> だければと思います。
> また、机のだいたいの大きさも、分かりましたら教えていただければと思います。
> よろしくお願いいたします。
