### ISSUE TITLE
Archクリスマス会

### ISSUE THREAD

**Issue by miyukki** [sfc-arch/documents#24]

**Comment by miyukki** [comment]
@sfc-arch/owners やる？やらない？

**Comment by demmys** [comment]
やる！

**Comment by pasora** [comment]
[![LGTM](http://lgtm.in/p/wyLueHLpq)](http://lgtm.in/i/wyLueHLpq)

**Comment by pasora** [comment]
Arch Christmas Party 参加者リスト:  @demmy: @miyukki @shunkin @usk @yatty @itochan @gentam @tukashu @naohiro @phi @aky @seibe @gomachan @pasora

**Comment by pasora** [comment]
参加者 += @cookie

**Comment by pasora** [comment]
とても関係ない人に mention 飛ばしているみたいで申し訳ないです

**Comment by pasora** [comment]
|品名|単価[円]|数量|備考|
|:---|---:|---:|:---|
|[ケンタッキークリスマスバーレル オリジナル](http://www.kfc.co.jp/campaign/xmas2015/menu.html)|4090|2|チキン8つ、サラダ、チョコレートケーキ、絵皿|
|[コージーコーナー 6つのクリスマスアソート](https://xmas.cozycorner.co.jp/xmascake/partycake)|2484|2|6人分|
|[コージーコーナー 4つのクリスマスアソート](https://xmas.cozycorner.co.jp/xmascake/partycake)|1998|1|4人分|
あとはヨーカドーで飲み物惣菜等
1人1100円〜1500円を予定しています

**Comment by miyukki** [comment]
ショコラリース のほうがコスパ良くない？

**Comment by pasora** [comment]
たしかに

**Comment by demmys** [comment]
@pasora 去年はケンタッキーのはクリスマスバーレルだとチキン少ないしケーキは別で買うからってことでチキンばっかりのセットにしてたけど、今回はそうはしない？

**Comment by pasora** [comment]
コストコで買おう案がほぼ採用に
