### ISSUE TITLE
GitHub EducationでのOrganization Accountの申請

### ISSUE THREAD

**Issue by seibe** [sfc-arch/documents#3]
大学組織なら無料でprivate orgnizationを作れる話。

ここら辺が参考になりそう。
http://qiita.com/gishi_yama/items/55be53d8a52c7304563a
http://pastak.hatenablog.com/entry/2014/03/02/225846

**Comment by miyukki** [comment]
# Waiting for good review :laughing: 
![screenshot 2015-04-09 22 14 59](https://cloud.githubusercontent.com/assets/720609/7067399/f0d01d24-df05-11e4-8c05-7f3f64ef18f2.png)

**Comment by miyukki** [comment]
:clap:
