### ISSUE TITLE
ORF2016の出展内容を決める @pasora

### ISSUE THREAD

**Issue by miyukki** [sfc-arch/documents#30]

**Comment by pasora** [comment]
出展します

**Comment by Akkyie** [comment]
出すンゴ

**Comment by miyukki** [comment]
でちゃう

**Comment by ndac-todoroki** [comment]
出

**Comment by Phi-phi** [comment]
できたら・・・・

**Comment by usk83** [comment]
1回くらいだしたいなあ

**Comment by Restar9** [comment]
だしたい(・∀・)

**Comment by syaro** [comment]
イク

**Comment by pasora** [comment]
プロジェクトタイトル(和文)
プロジェクトタイトル(英文)
プロジェクト概要(和文)(250文字)
プロジェクト概要(英文)(800文字 100語程度)
関連URL
担当者氏名(和文)
担当者氏名(英文)
担当者所属(学部)
Web掲載用画像(1000ピクセル四方以上のJPEG画像ファイル)

**Comment by pasora** [comment]
* タイトル (和文・英文)
Arch研究グループ
Arch research group

* 概要（和文250文字、英文800文字まで）
Archは次世代のネットワークおよびコンピュータ・アーキテクチャの実装と運用について研究しているグループです。
We propose, build and manage the next-generation network architecture and computer architecture. 

* 関連URL（任意）
arch.sfc.wide.ad.jp

* 担当者氏名（和文・英文）
pasora

* 担当者所属
環境情報学部

* Web掲載用画像
Archロゴ

**Comment by pasora** [comment]
* タイトル（和文・英文）
遠隔スイッチング可能な低遅延4K映像IP伝送システム
Remote switchable low-latency 4K video over IP.

* 概要（和文250文字、英文800文字まで）
```
映像制作の分野においては、カメラの映像をマトリックスルーターやスイッチャーまで同軸ケーブルを通すのが一般的です。しかし、これらの物理的な距離は離れているためコストの掛かる同軸ケーブルが必要であり、映像ソースを追加する場合や4K映像を扱う場合には、新たに同軸ケーブル通す必要があります。

本システムでは、これらの問題を解決するため、IP網を利用した高繊細な4K映像の低遅延伝送を可能としています。

```
```
In the field of video production, it is common that the cameras connect to the matrix or switcher using coaxial cable.
However, the usage of coaxial cable takes a cost when adding another video sources or changing the high resolution video.

This system is able to transmit low-latency 4K video over IP.
```

* 関連URL（任意）
arch.sfc.wide.ad.jp

* 担当者氏名（和文・英文）
山中 勇成
Yusei Yamanaka

* 担当者所属
環境情報学部

**Comment by pasora** [comment]
usk, syaro(?) をマイナス
