### ISSUE TITLE
ミッドタウンに送る荷物を整理する

### ISSUE THREAD

**Issue by pasora** [sfc-arch/documents#31]

**Comment by pasora** [comment]
|もの|かず|びこう|
|:--:|:--:|:--:|
|ディスプレイ|1|デルタにある|
|電源タップ|1|デルタにある|

* ダンボールの数(概算)…1つ

**Comment by Akkyie** [comment]
|もの|かず|びこう|
|:--:|:--:|:--:|
|ディスプレイ|1|デルタにある|

* ダンボールの数(概算)…1つ（だれかのとまとめたい）

**Comment by pasora** [comment]
そういえばダンボールは支給があるはずなんだけどまだ見てないからダンボールの数なんて今決めてもしょうがないかもー

**Comment by pasora** [comment]
sorry for missing closing and thank you

**Comment by akkyie** [comment]
@pasora 👍
