### ISSUE TITLE
sfc-arch OrganizationのロゴをArch新ロゴにする

### ISSUE THREAD

**Issue by demmys** [sfc-arch/documents#4]
正方形画像を用意する必要があるみたいです。
最適なサイズが幾つかは知らない。

**Comment by demmys** [comment]
@seibe せいべえ先生、お願いします!

**Comment by miyukki** [comment]
archbotの正方形ロゴもそれにしたい

**Comment by seibe** [comment]
ぜんぶArch botに合わせれば……

**Comment by demmys** [comment]
@seibe パクリいくない

**Comment by seibe** [comment]
あしたやる

**Comment by seibe** [comment]
https://github.com/sfc-arch/documents/blob/master/assets/logo/arch_square.png

**Comment by seibe** [comment]
設定done.
