### ISSUE TITLE
phiとcookieの親を決める

### ISSUE THREAD

**Issue by demmys** [sfc-arch/documents#6]
今期はphiとcookieがWIP必須となるため、親を決める必要が出てきます。

**Comment by demmys** [comment]
@pasora 
適切なタイミングでミーティングアジェンダに組み込まれるようアレンジしてください

**Comment by miyukki** [comment]
@demmys ping

**Comment by demmys** [comment]
毎週順に発表する形式になったので自ずと決まりそうだしclose.
