### ISSUE TITLE
新人をArch@MLに登録する

### ISSUE THREAD

**Issue by miyukki** [sfc-arch/documents#8]

**Comment by seibe** [comment]
@demmys リマインド

**Comment by demmys** [comment]
@seibe 
忘れてた。done.

@Akkyie @so-ta 
MLに登録したので確認よろしく。
メール文に登録してねって書いたけど、もう入れてるみたい。

rheniumがGithub上でなんていう名前なのかわからない...

**Comment by Akkyie** [comment]
@demmys Closedに書くのもアレなんですけど、それらしいメールを受け取ってないっぽいのですが大丈夫ですかね

**Comment by demmys** [comment]
@Akkyie あれ、行かないもんなのかも。いまArch MLでメール送ってみたから aky@sfc.wide.ad.jp のアドレスを確認してみてー！

**Comment by Akkyie** [comment]
来ました！ありがとうございますー

**Comment by demmys** [comment]
よかった
